### ISSUE TITLE
Ability to designate code reviewers and code approvers for PRs

### ISSUE THREAD

**Issue by lax0248917** [TeamArmadilloOrg/teamWebsite#14]
Need help finding a way to have github request a review from every team member when a pull request is created, but only allow the Product Owner and Lead Developers to approve code for merge. Currently Codeowners are set to the Product Owner and the Lead Developers, the develop branch requires at least 2 approvals from a Code Owner.  So that piece functions correctly however it is the CODEOWNER file that automatically adds everyone as a reviewer. So now since everyone is not a part of that file we need to find a new way of having everyone else added to the review process. 

As of right now, you can request the remaining team members manually. I did create a team in our ORG named "Armadillo-TAWS" and added everyone to it. You can request a review from the team, whether this adds everyone I am not sure. We will have to try it. I do know that we can set required reviews up to a number of 3 members of a team and set it to do "Round Robin" on who it will automatically add to the pull request, its not perfect but an option.

No idea is a bad one!

**Comment by xeho91** [comment]
Splitting into our internal teams (Lead developers, design team, dev team) is not going to resolve this case?

**Comment by lax0248917** [comment]
I am not sure but it is worth a try. Let me do some configuration changes in github and once that it done, would you like to test it?

**Comment by lax0248917** [comment]
3 new Teams have been added. Lead Dev Team, Design Team and Dev Team. Added members, so now we can give it a try it out by adding the designated team to the reviews.

**Comment by xeho91** [comment]
Seeing the latest Pull Request from Marius, I assume this is working as expected right now, correct?

**Comment by lax0248917** [comment]
I am not sure since the two of us were the only ones assigned the review. I would like to test this where another team is selected and see if it adds the whole group.

**Comment by lax0248917** [comment]
This issue was resolved in a previous pull request. Team has agreed on the use of Codeowners for the Lead Dev team and the Product owner. All other reviewers will be added manually using the designated team. Closing issue
