### ISSUE TITLE
Currently proposed project structure is not "future-proof"

### ISSUE THREAD

**Issue by xeho91** [TeamArmadilloOrg/teamWebsite#5]
First of all, I didn't know which adjective would perfectly describe the current issue.
Because of the fact that English isn't my first language, so I often use google translator and Grammarly, to correct my mistakes.
Of course, I came up the word in my native language, used a translator, and it suggested the word "reckless". I said no, this has too negative vibe! 😅

I have made comment to last pull request #4 made by @brndndev. Unfortunately, the request was approved in the rush before I could share my feedback, so I'll paste it again here (with little edits), to open a new discussion about it.

I have a little experience with creating projects so far, thanks to the fact that I've been doing some personal small project challenges recently. So, I'll share my thoughts, just to share my knowledge and provide some constructive feedback.

### Let's begin!
--
**We shouldn't put our _'source'_ files with code in the root directory `./`.**

These files @brndndev created (app.js, index.html and styles.css) should be put inside the folder, which other experienced developers usually call it "**src**".
However, for the learning purposes, **I really want to avoid abbreviations**, so I would name it in the most understandable way for every beginner "`source`".

When our project gets a little more complex... with more files such as configurations for ESlint, git, bundlers such as webpack/Rollup, Babel, etc.
Without a doubt, we will have to create subpages (templates), split codes in JS/CSS for better readability. You wouldn't want them to put everything inside one directory (root), as this will be an organisational mess. 

I also propose to create other subfolders inside the `./source` folder (directory), where we will separate our assets for the website, such as `images`, `styles`, `scripts`, `data`, etc.

Besides this, we will have **a "build" output** of our work (code) based on the _"environment"_. According to my research and studies, there are these environments (the first two, are the most common I have encountered):

1. - **production**, 
2. - **development**
4. - sometimes they also add **staged** (or **testing** ?)

To describe them shortly:

- **production** - where the code is ready and available for public usage. The assets are "minimized", "minified" (for performance purposes). etc.
Is a very common practice to generate the output inside the folder `./public` or `./build/public`.
Later the output inside this directory can be "deployed" to our hosting server.
- **development** - the assets are not minimized (usually). They're processed by bundlers such as webpack, rollup, etc.  Everything there is for the purpose to develop a new feature(s). So, it's okay if stuff may not be working here.
- **staged/testing** - in the middle between development and production. For testing purposes, to ensure that we don't encounter any bugs in the "optimization for performance" process.

### Below is an example project structure tree, which I propose to follow.
```
.
├── .gitignore
├── README.md
├── LICENSE
├── package.json
├── build
│   ├── development
│   ├── public
│   └── staged
└── source
    ├── index.html
    ├── data
    │   └── database.json
    ├── images
    │   └── background.jpg
    ├── scripts
    │   └── app.js
    └── styles
        └── style.css
```

**Comment by lax0248917** [comment]
I like @brndndev drive and determination to work through the git flow process. Pull request #4 was a great learning experience. 

@xeho91 your file structure suggestions is spot on and I appreciate you showing us a more robust setup. And for taking into consideration the longevity of our site. We should be thinking long-term straight from the start. Thank you. I am good with making these structural changes
